---
- name: "ANSSI | Kernel | Application des paramètres anti-hacking"
  become: true
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - { key: "net.ipv4.conf.all.accept_redirects", value: "0" } 
    - { key: "kernel.dmesg_restrict", value: "1" }              
    - { key: "kernel.randomize_va_space", value: "2" }          

- name: "ANSSI | Bannière | Avertissement Légal Défense"
  become: true
  ansible.builtin.copy:
    dest: /etc/issue.net
    content: |
      ===========================================================
      ⚠️ SYSTÈME D'INFORMATION RESTREINT EXAIL (V2) ⚠️
      Toute intrusion est traçable et pénalement répréhensible.
      ===========================================================
