---
- name: "Podman | Installation"
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: true
  become: true

- name: "Sécurité | Création compte service"
  ansible.builtin.user:
    name: "{{ podman_service_user }}"
    shell: /sbin/nologin
    create_home: true
  become: true

- name: "Air-Gapped | Transfert des archives .tar vers la VM"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ podman_transfer_dir }}/{{ item }}"
    mode: "0600"
    owner: "{{ podman_service_user }}"
    group: "{{ podman_service_user }}"
  loop:
    - exail-backend.tar
    - exail-frontend.tar
  become: true

- name: "Podman | Chargement images (en tant que {{ podman_service_user }})"
  ansible.builtin.command: "podman load -i {{ podman_transfer_dir }}/{{ item }}"
  loop:
    - exail-backend.tar
    - exail-frontend.tar
  register: load_result
  changed_when: true
  become: true
  become_user: "{{ podman_service_user }}"

- debug:
    var: load_result.results

- name: "Récupérer le tag du backend chargé"
  ansible.builtin.shell: podman images --format "{{ '{{' }}.Repository}}:{{ '{{' }}.Tag}}" | grep exail-backend | head -1
  register: backend_image_tag
  changed_when: false
  become: true
  become_user: "{{ podman_service_user }}"

- name: "Récupérer le tag du frontend chargé"
  ansible.builtin.shell: podman images --format "{{ '{{' }}.Repository}}:{{ '{{' }}.Tag}}" | grep exail-frontend | head -1
  register: frontend_image_tag
  changed_when: false
  become: true
  become_user: "{{ podman_service_user }}"

- name: "Lancement du Backend C++"
  ansible.builtin.shell: |
    podman rm -f exail-backend 2>/dev/null || true
    podman run -d \
      --name exail-backend \
      --cap-drop ALL \
      -p {{ ufw_backend_port }}:{{ container_backend_port }} \
      {{ backend_image_tag.stdout }}
  register: backend_run
  changed_when: true
  become: true
  become_user: "{{ podman_service_user }}"

- name: "Lancement du Frontend Vue.js"
  ansible.builtin.shell: |
    podman rm -f exail-frontend 2>/dev/null || true
    podman run -d \
      --name exail-frontend \
      --cap-drop ALL \
      -p {{ ufw_frontend_port }}:{{ container_frontend_port }} \
      {{ frontend_image_tag.stdout }}
  changed_when: true
  become: true
  become_user: "{{ podman_service_user }}"

- name: "Nettoyage | Suppression archives .tar de /tmp"
  ansible.builtin.file:
    path: "{{ podman_transfer_dir }}/{{ item }}"
    state: absent
  loop:
    - exail-backend.tar
    - exail-frontend.tar
  become: true
