---
- name: "Podman | Installation"
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: true

- name: "Sécurité | Création compte service exail_svc"
  ansible.builtin.user:
    name: exail_svc
    shell: /sbin/nologin
    create_home: true

- name: "Air-Gapped | Transfert des archives .tar vers la VM"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0600'
  loop:
    - exail-backend.tar
    - exail-frontend.tar

- name: "Podman | Chargement images"
  ansible.builtin.command: "podman load -i /tmp/{{ item }}"
  loop:
    - exail-backend.tar
    - exail-frontend.tar
  register: load_result
  changed_when: true

- debug:
    var: load_result.results

- name: "Récupérer le tag du backend chargé"
  ansible.builtin.shell: podman images --format "{{ '{{' }}.Repository}}:{{ '{{' }}.Tag}}" | grep exail-backend | head -1
  register: backend_image_tag
  changed_when: false

- name: "Récupérer le tag du frontend chargé"
  ansible.builtin.shell: podman images --format "{{ '{{' }}.Repository}}:{{ '{{' }}.Tag}}" | grep exail-frontend | head -1
  register: frontend_image_tag
  changed_when: false


- name: "Lancement du Backend C++"
  ansible.builtin.shell: |
    podman rm -f exail-backend 2>/dev/null || true
    podman run -d \
      --name exail-backend \
      --cap-drop ALL \
      -p 9090:9090 \
      {{ backend_image_tag.stdout }}
  register: backend_run
  changed_when: true
- name: "Debug backend run"
  debug:
    var: backend_run
- name: "Lancement du Frontend Vue.js"
  ansible.builtin.shell: |
    podman rm -f exail-frontend 2>/dev/null || true
    podman run -d \
      --name exail-frontend \
      --cap-drop ALL \
      -p 8080:8080 \
      {{ frontend_image_tag.stdout }}
  changed_when: true
  ignore_errors: true

- name: "Nettoyage | Suppression archives .tar de /tmp"
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - exail-backend.tar
    - exail-frontend.tar