---
- name: "DevSecOps Exail — Hardening OS"
  hosts: all:!monitoring
  become: true
  tags: [os-hardening]
  roles:
    - os-hardening

- name: "DevSecOps Exail — Déploiement Applicatif (Air-Gapped)"
  hosts: all:!monitoring
  become: false
  tags: [deploy]
  roles:
    - podman-deploy

- name: "DevSecOps Exail — Observabilité (Stack Monitoring)"
  hosts: all
  become: true
  tags: [observability]
  roles:
    - observability
