---
- name: "DevSecOps Exail — Hardening OS"
  hosts: all
  become: true
  roles:
    - os-hardening

- name: "DevSecOps Exail — Déploiement Applicatif (Air-Gapped)"
  hosts: all
  become: false
  roles:
    - podman-deploy

- name: "DevSecOps Exail — Observabilité (Stack Monitoring)"
  hosts: all
  become: true
  roles:
    - observability